pragma Singleton
import QtQuick

QtObject {
    property color primary: "#aed18d"
    property color surfaceTint: "#aed18d"
    property color on_Primary: "#1c3703"
    property color primaryContainer: "#324e18"
    property color on_PrimaryContainer: "#caeea6"
    property color secondary: "#becbae"
    property color on_Secondary: "#29341f"
    property color secondaryContainer: "#3f4a34"
    property color on_SecondaryContainer: "#dae7c9"
    property color tertiary: "#a0cfcd"
    property color on_Tertiary: "#003736"
    property color tertiaryContainer: "#1e4e4d"
    property color on_TertiaryContainer: "#bbece9"
    property color error: "#ffb4ab"
    property color on_Error: "#690005"
    property color errorContainer: "#93000a"
    property color on_ErrorContainer: "#ffdad6"
    property color background: "#11140e"
    property color on_Background: "#e2e3d9"
    property color surface: "#11140e"
    property color on_Surface: "#e2e3d9"
    property color surfaceVariant: "#44483e"
    property color on_SurfaceVariant: "#c4c8ba"
    property color outline: "#8e9286"
    property color outlineVariant: "#44483e"
    property color shadow: "#000000"
    property color scrim: "#000000"
    property color inverseSurface: "#e2e3d9"
    property color inverseon_Surface: "#2e312a"
    property color inversePrimary: "#49672e"
    property color primaryFixed: "#caeea6"
    property color on_PrimaryFixed: "#0d2000"
    property color primaryFixedDim: "#aed18d"
    property color on_PrimaryFixedVariant: "#324e18"
    property color secondaryFixed: "#dae7c9"
    property color on_SecondaryFixed: "#151e0c"
    property color secondaryFixedDim: "#becbae"
    property color on_SecondaryFixedVariant: "#3f4a34"
    property color tertiaryFixed: "#bbece9"
    property color on_TertiaryFixed: "#00201f"
    property color tertiaryFixedDim: "#a0cfcd"
    property color on_TertiaryFixedVariant: "#1e4e4d"
    property color surfaceDim: "#11140e"
    property color surfaceBright: "#373a33"
    property color surfaceContainerLowest: "#0c0f09"
    property color surfaceContainerLow: "#1a1d16"
    property color surfaceContainer: "#1e211a"
    property color surfaceContainerHigh: "#282b24"
    property color surfaceContainerHighest: "#33362e"

    // Font
    property string font: "JetBrainsMono NFM"
}
