pragma Singleton
import QtQuick

QtObject {
    property color primary: "#9CCBFB"
    property color surfaceTint: "#9CCBFB"
    property color on_Primary: "#003354"
    property color primaryContainer: "#114A73"
    property color on_PrimaryContainer: "#CFE5FF"
    property color secondary: "#B9C8DA"
    property color on_Secondary: "#243240"
    property color secondaryContainer: "#3A4857"
    property color on_SecondaryContainer: "#D5E4F7"
    property color tertiary: "#D4BEE6"
    property color on_Tertiary: "#392A49"
    property color tertiaryContainer: "#504061"
    property color on_TertiaryContainer: "#EFDBFF"
    property color error: "#FFB4AB"
    property color on_Error: "#690005"
    property color errorContainer: "#93000A"
    property color on_ErrorContainer: "#FFDAD6"
    property color background: "#101418"
    property color on_Background: "#E0E2E8"
    property color surface: "#101418"
    property color on_Surface: "#E0E2E8"
    property color surfaceVariant: "#42474E"
    property color on_SurfaceVariant: "#C2C7CF"
    property color outline: "#8C9199"
    property color outlineVariant: "#42474E"
    property color shadow: "#000000"
    property color scrim: "#000000"
    property color inverseSurface: "#E0E2E8"
    property color inverseon_Surface: "#2D3135"
    property color inversePrimary: "#30628C"
    property color primaryFixed: "#CFE5FF"
    property color on_PrimaryFixed: "#001D33"
    property color primaryFixedDim: "#9CCBFB"
    property color on_PrimaryFixedVariant: "#114A73"
    property color secondaryFixed: "#D5E4F7"
    property color on_SecondaryFixed: "#0E1D2A"
    property color secondaryFixedDim: "#B9C8DA"
    property color on_SecondaryFixedVariant: "#3A4857"
    property color tertiaryFixed: "#EFDBFF"
    property color on_TertiaryFixed: "#231533"
    property color tertiaryFixedDim: "#D4BEE6"
    property color on_TertiaryFixedVariant: "#504061"
    property color surfaceDim: "#101418"
    property color surfaceBright: "#36393E"
    property color surfaceContainerLowest: "#0B0E12"
    property color surfaceContainerLow: "#181C20"
    property color surfaceContainer: "#1C2024"
    property color surfaceContainerHigh: "#272A2F"
    property color surfaceContainerHighest: "#323539"


    // Font
    property string font: "JetBrainsMono NFM"
}
